repos:
  - repo: https://github.com/mushdavtyan/terraform-aws-ec2-backup
    rev: master
    hooks:
      - id: terraform_fmt
      # Git style
      - id: check-added-large-files # prevents giant files from being committed.
      - id: forbid-new-submodules # prevents addition of new git submodules.
      - id: no-commit-to-branch # don't commit to branch
      # Common errors
      - id: trailing-whitespace # trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
